import Footer from '#/shared/components/layout/Footer'
import Navbar from '#components/layout/Navbar'
import '#styles/globals.scss'

export const metadata = {
  title: 'Bauztel - Website',
  description: 'Generated by create next app',
}

const RootLayout: FC = ({ children }) => {
  return (
    <html lang='es'>
      <body>
        <Navbar />
        <div className="container">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}

export default RootLayout
